// Semestre 2/Missão_Pratica_-_Nivel_5/livro-servidor/clientes/livros-react/src/LivroDados.js
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivro } from './controle/ControleLivros';
import { ControleEditora } from './controle/ControleEditora';

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

const LivroDados = () => {
    const [opcoes] = useState(controleEditora.getEditoras().map(editora => ({ value: editora.codEditora, text: editora.nome })));
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0]?.value);
    const navigate = useNavigate();

    const tratarCombo = (event) => {
        setCodEditora(Number(event.target.value));
    };

    const incluir = () => {
        const novoLivro = new Livro("", titulo, resumo, autores);
        controleLivros.incluir(novoLivro).then(() => navigate('/'));
    };

    return (
        <main>
            <h1>Cadastro de Livro</h1>
            <form onSubmit={incluir}>
                <div className="form-group">
                    <label htmlFor="titulo">Título:</label>
                    <input type="text" className="form-control" id="titulo" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </div>
                <div className="form-group">
                    <label htmlFor="resumo">Resumo:</label>
                    <textarea className="form-control" id="resumo" value={resumo} onChange={(e) => setResumo(e.target.value)}></textarea>
                </div>
                <div className="form-group">
                    <label htmlFor="autores">Autores (um por linha):</label>
                    <textarea className="form-control" id="autores" value={autores} onChange={(e) => setAutores(e.target.value)}></textarea>
                </div>
                <div className="form-group">
                    <label htmlFor="editora">Editora:</label>
                    <select className="form-control" id="editora" value={codEditora} onChange={tratarCombo}>
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                        ))}
                    </select>
                </div>
                <button type="submit" className="btn btn-primary">Salvar</button>
            </form>
        </main>
    );
};

export default LivroDados;

// Semestre 2/Missão_Pratica_-_Nivel_5/livro-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class="container">
    <h2>Adicionar Novo Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" required [(ngModel)]="livro.titulo" name="titulo">
      </div>
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" rows="3" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select class="form-control" id="editora" required [(ngModel)]="livro.codEditora" name="editora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores (um por linha):</label>
        <textarea class="form-control" id="autores" rows="3" [(ngModel)]="autoresForm" name="autores"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Adicionar Livro</button>
    </form>
  </main>
